# Generated by Django 4.1.6 on 2023-02-10 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('auth_id', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(default='', max_length=200)),
                ('place', models.CharField(default='', max_length=200)),
                ('nationality', models.CharField(default='', max_length=200)),
                ('yob', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('yop', models.CharField(default='', max_length=200)),
                ('publisher', models.CharField(default='', max_length=200)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to='book_central.author')),
            ],
        ),
    ]
