# Generated by Django 4.1.6 on 2023-02-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Details',
        ),
    ]
